// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkAKponflz5YP-HYzF6E28MUIsxJlbCT8',
    appId: '1:1025915007674:web:64ef6cbb7ca2aaa1298883',
    messagingSenderId: '1025915007674',
    projectId: 'farm-manager-app-9d748',
    authDomain: 'farm-manager-app-9d748.firebaseapp.com',
    storageBucket: 'farm-manager-app-9d748.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWsE4odTj-ye9KN8OzskVMw5p-NCoPQkM',
    appId: '1:1025915007674:android:1f1c1193189195df298883',
    messagingSenderId: '1025915007674',
    projectId: 'farm-manager-app-9d748',
    storageBucket: 'farm-manager-app-9d748.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCka9QXs5I31XoT6A275Fw6bxRgnxOcI_s',
    appId: '1:1025915007674:ios:6c0632f64ee4dfca298883',
    messagingSenderId: '1025915007674',
    projectId: 'farm-manager-app-9d748',
    storageBucket: 'farm-manager-app-9d748.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCka9QXs5I31XoT6A275Fw6bxRgnxOcI_s',
    appId: '1:1025915007674:ios:6c0632f64ee4dfca298883',
    messagingSenderId: '1025915007674',
    projectId: 'farm-manager-app-9d748',
    storageBucket: 'farm-manager-app-9d748.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkAKponflz5YP-HYzF6E28MUIsxJlbCT8',
    appId: '1:1025915007674:web:62b92fde46f14916298883',
    messagingSenderId: '1025915007674',
    projectId: 'farm-manager-app-9d748',
    authDomain: 'farm-manager-app-9d748.firebaseapp.com',
    storageBucket: 'farm-manager-app-9d748.firebasestorage.app',
  );
}
